<?php

// DO NOT MODIFY. This file is automatically generated.

/**
 * Get the background color for a specific CSS theme.
 *
 * @param string $theme The theme name
 *
 * @throws \DomainException when no stylesheet with this name exists
 *
 * @return string
 */
function _getThemeBackgroundColor($theme)
{
    $colors = array(
        'a11y-dark' => '#2b2b2b',
        'a11y-light' => '#fefefe',
        'agate' => '#333',
        'an-old-hope' => '#1c1d21',
        'androidstudio' => '#282b2e',
        'arduino-light' => '#fff',
        'arta' => '#222',
        'ascetic' => '#ffffff',
        'atelier-cave-dark' => '#19171c',
        'atelier-cave-light' => '#efecf4',
        'atelier-dune-dark' => '#20201d',
        'atelier-dune-light' => '#fefbec',
        'atelier-estuary-dark' => '#22221b',
        'atelier-estuary-light' => '#f4f3ec',
        'atelier-forest-dark' => '#1b1918',
        'atelier-forest-light' => '#f1efee',
        'atelier-heath-dark' => '#1b181b',
        'atelier-heath-light' => '#f7f3f7',
        'atelier-lakeside-dark' => '#161b1d',
        'atelier-lakeside-light' => '#ebf8ff',
        'atelier-plateau-dark' => '#1b1818',
        'atelier-plateau-light' => '#f4ecec',
        'atelier-savanna-dark' => '#171c19',
        'atelier-savanna-light' => '#ecf4ee',
        'atelier-seaside-dark' => '#131513',
        'atelier-seaside-light' => '#f4fbf4',
        'atelier-sulphurpool-dark' => '#202746',
        'atelier-sulphurpool-light' => '#f5f7ff',
        'atom-one-dark-reasonable' => '#282c34',
        'atom-one-dark' => '#282c34',
        'atom-one-light' => '#fafafa',
        'brown-paper' => '#ffffff',
        'codepen-embed' => '#222',
        'color-brewer' => '#fff',
        'darcula' => '#2b2b2b',
        'dark' => '#444',
        'darkula' => '#ffffff',
        'default' => '#f0f0f0',
        'docco' => '#f8f8ff',
        'dracula' => '#282a36',
        'far' => '#000080',
        'foundation' => '#eee',
        'github-gist' => '#ffffff',
        'github' => '#f8f8f8',
        'gml' => '#222',
        'googlecode' => '#ffffff',
        'gradient-dark' => '#501f7a',
        'grayscale' => '#fff',
        'gruvbox-dark' => '#282828',
        'gruvbox-light' => '#fbf1c7',
        'hopscotch' => '#322931',
        'hybrid' => '#1d1f21',
        'idea' => '#fff',
        'ir-black' => '#000',
        'isbl-editor-dark' => '#404040',
        'isbl-editor-light' => '#ffffff',
        'kimbie.dark' => '#221a0f',
        'kimbie.light' => '#fbebd4',
        'lightfair' => '#ffffff',
        'magula' => '#f4f4f4',
        'mono-blue' => '#eaeef3',
        'monokai-sublime' => '#23241f',
        'monokai' => '#272822',
        'night-owl' => '#011627',
        'nord' => '#2e3440',
        'obsidian' => '#282b2e',
        'ocean' => '#2b303b',
        'paraiso-dark' => '#2f1e2e',
        'paraiso-light' => '#e7e9db',
        'pojoaque' => '#ffffff',
        'purebasic' => '#ffffdf',
        'qtcreator_dark' => '#000',
        'qtcreator_light' => '#fff',
        'railscasts' => '#232323',
        'rainbow' => '#474949',
        'routeros' => '#f0f0f0',
        'school-book' => '#ffffff',
        'shades-of-purple' => '#2d2b57',
        'solarized-dark' => '#002b36',
        'solarized-light' => '#fdf6e3',
        'sunburst' => '#000',
        'tomorrow-night-blue' => '#002451',
        'tomorrow-night-bright' => '#ffffff',
        'tomorrow-night-eighties' => '#2d2d2d',
        'tomorrow-night' => '#1d1f21',
        'tomorrow' => '#ffffff',
        'vs' => '#ffffff',
        'vs2015' => '#1e1e1e',
        'xcode' => '#fff',
        'xt256' => '#000',
        'zenburn' => '#3f3f3f',
    );

    if (!isset($colors[$theme])) {
        throw new DomainException("There is no stylesheet by the name of '$theme'");
    }

    return $colors[$theme];
}
