<?php

namespace HighlightUtilities;

/**
 * Convert the HTML generated by Highlighter and split it up into an array of lines.
 *
 * @api
 *
 * @since 9.15.6.1
 *
 * @param string $html An HTML string generated by `Highlighter::highlight()`
 *
 * @throws \RuntimeException         when the DOM extension is not available
 * @throws \UnexpectedValueException when the given HTML could not be parsed
 *
 * @return string[]|false An array of lines of code as strings. False if an error occurred in splitting up by lines
 */
function splitCodeIntoArray($html)
{
    if (!extension_loaded("dom")) {
        throw new \RuntimeException("The DOM extension is not loaded but is required.");
    }

    $dom = new \DOMDocument();

    if (!$dom->loadHTML($html)) {
        throw new \UnexpectedValueException("The given HTML could not be parsed correctly.");
    }

    $spans = $dom->getElementsByTagName("span");

    /** @var \DOMElement $span */
    foreach ($spans as $span) {
        $classes = $span->getAttribute("class");
        $renderedSpan = $dom->saveHTML($span);

        if (preg_match('/\R/', $renderedSpan)) {
            $finished = preg_replace(
                '/\R/',
                sprintf('</span>%s<span class="%s">', PHP_EOL, $classes),
                $renderedSpan
            );
            $html = str_replace($renderedSpan, $finished, $html);
        }
    }

    return preg_split('/\R/', $html);
}
