<?php

// DO NOT MODIFY. This file is automatically generated.

/**
 * Get the background color for a specific CSS theme.
 *
 * @param string $theme The theme name
 *
 * @throws \DomainException when no stylesheet with this name exists
 *
 * @return float[]
 */
function _getThemeBackgroundColor($theme)
{
    $colors = array(
        'a11y-dark' => array(
            'r' => 43.0,
            'g' => 43.0,
            'b' => 43.0,
        ),
        'a11y-light' => array(
            'r' => 254.0,
            'g' => 254.0,
            'b' => 254.0,
        ),
        'agate' => array(
            'r' => 51.0,
            'g' => 51.0,
            'b' => 51.0,
        ),
        'an-old-hope' => array(
            'r' => 28.0,
            'g' => 29.0,
            'b' => 33.0,
        ),
        'androidstudio' => array(
            'r' => 40.0,
            'g' => 43.0,
            'b' => 46.0,
        ),
        'arduino-light' => array(
            'r' => 255,
            'g' => 255,
            'b' => 255,
        ),
        'arta' => array(
            'r' => 34.0,
            'g' => 34.0,
            'b' => 34.0,
        ),
        'ascetic' => array(
            'r' => 255,
            'g' => 255,
            'b' => 255,
        ),
        'atom-one-dark-reasonable' => array(
            'r' => 40.0,
            'g' => 44.0,
            'b' => 52.0,
        ),
        'atom-one-dark' => array(
            'r' => 40.0,
            'g' => 44.0,
            'b' => 52.0,
        ),
        'atom-one-light' => array(
            'r' => 250.0,
            'g' => 250.0,
            'b' => 250.0,
        ),
        3024 => array(
            'r' => 9.0,
            'g' => 3.0,
            'b' => 0.0,
        ),
        'apathy' => array(
            'r' => 3.0,
            'g' => 26.0,
            'b' => 22.0,
        ),
        'apprentice' => array(
            'r' => 38.0,
            'g' => 38.0,
            'b' => 38.0,
        ),
        'ashes' => array(
            'r' => 28.0,
            'g' => 32.0,
            'b' => 35.0,
        ),
        'atelier-cave-light' => array(
            'r' => 239.0,
            'g' => 236.0,
            'b' => 244.0,
        ),
        'atelier-cave' => array(
            'r' => 25.0,
            'g' => 23.0,
            'b' => 28.0,
        ),
        'atelier-dune-light' => array(
            'r' => 254.0,
            'g' => 251.0,
            'b' => 236.0,
        ),
        'atelier-dune' => array(
            'r' => 32.0,
            'g' => 32.0,
            'b' => 29.0,
        ),
        'atelier-estuary-light' => array(
            'r' => 244.0,
            'g' => 243.0,
            'b' => 236.0,
        ),
        'atelier-estuary' => array(
            'r' => 34.0,
            'g' => 34.0,
            'b' => 27.0,
        ),
        'atelier-forest-light' => array(
            'r' => 241.0,
            'g' => 239.0,
            'b' => 238.0,
        ),
        'atelier-forest' => array(
            'r' => 27.0,
            'g' => 25.0,
            'b' => 24.0,
        ),
        'atelier-heath-light' => array(
            'r' => 247.0,
            'g' => 243.0,
            'b' => 247.0,
        ),
        'atelier-heath' => array(
            'r' => 27.0,
            'g' => 24.0,
            'b' => 27.0,
        ),
        'atelier-lakeside-light' => array(
            'r' => 235.0,
            'g' => 248.0,
            'b' => 255.0,
        ),
        'atelier-lakeside' => array(
            'r' => 22.0,
            'g' => 27.0,
            'b' => 29.0,
        ),
        'atelier-plateau-light' => array(
            'r' => 244.0,
            'g' => 236.0,
            'b' => 236.0,
        ),
        'atelier-plateau' => array(
            'r' => 27.0,
            'g' => 24.0,
            'b' => 24.0,
        ),
        'atelier-savanna-light' => array(
            'r' => 236.0,
            'g' => 244.0,
            'b' => 238.0,
        ),
        'atelier-savanna' => array(
            'r' => 23.0,
            'g' => 28.0,
            'b' => 25.0,
        ),
        'atelier-seaside-light' => array(
            'r' => 244.0,
            'g' => 251.0,
            'b' => 244.0,
        ),
        'atelier-seaside' => array(
            'r' => 19.0,
            'g' => 21.0,
            'b' => 19.0,
        ),
        'atelier-sulphurpool-light' => array(
            'r' => 245.0,
            'g' => 247.0,
            'b' => 255.0,
        ),
        'atelier-sulphurpool' => array(
            'r' => 32.0,
            'g' => 39.0,
            'b' => 70.0,
        ),
        'atlas' => array(
            'r' => 0.0,
            'g' => 38.0,
            'b' => 53.0,
        ),
        'bespin' => array(
            'r' => 40.0,
            'g' => 33.0,
            'b' => 28.0,
        ),
        'black-metal-bathory' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-burzum' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-dark-funeral' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-gorgoroth' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-immortal' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-khold' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-marduk' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-mayhem' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-nile' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal-venom' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'black-metal' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'brewer' => array(
            'r' => 12.0,
            'g' => 13.0,
            'b' => 14.0,
        ),
        'bright' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'brogrammer' => array(
            'r' => 31.0,
            'g' => 31.0,
            'b' => 31.0,
        ),
        'brush-trees-dark' => array(
            'r' => 72.0,
            'g' => 88.0,
            'b' => 103.0,
        ),
        'brush-trees' => array(
            'r' => 227.0,
            'g' => 239.0,
            'b' => 239.0,
        ),
        'chalk' => array(
            'r' => 21.0,
            'g' => 21.0,
            'b' => 21.0,
        ),
        'circus' => array(
            'r' => 25.0,
            'g' => 25.0,
            'b' => 25.0,
        ),
        'classic-dark' => array(
            'r' => 21.0,
            'g' => 21.0,
            'b' => 21.0,
        ),
        'classic-light' => array(
            'r' => 245.0,
            'g' => 245.0,
            'b' => 245.0,
        ),
        'codeschool' => array(
            'r' => 35.0,
            'g' => 44.0,
            'b' => 49.0,
        ),
        'colors' => array(
            'r' => 17.0,
            'g' => 17.0,
            'b' => 17.0,
        ),
        'cupcake' => array(
            'r' => 251.0,
            'g' => 241.0,
            'b' => 242.0,
        ),
        'cupertino' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'danqing' => array(
            'r' => 45.0,
            'g' => 48.0,
            'b' => 47.0,
        ),
        'darcula' => array(
            'r' => 43.0,
            'g' => 43.0,
            'b' => 43.0,
        ),
        'dark-violet' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'darkmoss' => array(
            'r' => 23.0,
            'g' => 30.0,
            'b' => 31.0,
        ),
        'darktooth' => array(
            'r' => 29.0,
            'g' => 32.0,
            'b' => 33.0,
        ),
        'decaf' => array(
            'r' => 45.0,
            'g' => 45.0,
            'b' => 45.0,
        ),
        'default-dark' => array(
            'r' => 24.0,
            'g' => 24.0,
            'b' => 24.0,
        ),
        'default-light' => array(
            'r' => 248.0,
            'g' => 248.0,
            'b' => 248.0,
        ),
        'dirtysea' => array(
            'r' => 224.0,
            'g' => 224.0,
            'b' => 224.0,
        ),
        'dracula' => array(
            'r' => 40.0,
            'g' => 41.0,
            'b' => 54.0,
        ),
        'edge-dark' => array(
            'r' => 38.0,
            'g' => 39.0,
            'b' => 41.0,
        ),
        'edge-light' => array(
            'r' => 250.0,
            'g' => 250.0,
            'b' => 250.0,
        ),
        'eighties' => array(
            'r' => 45.0,
            'g' => 45.0,
            'b' => 45.0,
        ),
        'embers' => array(
            'r' => 22.0,
            'g' => 19.0,
            'b' => 15.0,
        ),
        'equilibrium-dark' => array(
            'r' => 12.0,
            'g' => 17.0,
            'b' => 24.0,
        ),
        'equilibrium-gray-dark' => array(
            'r' => 17.0,
            'g' => 17.0,
            'b' => 17.0,
        ),
        'equilibrium-gray-light' => array(
            'r' => 241.0,
            'g' => 241.0,
            'b' => 241.0,
        ),
        'equilibrium-light' => array(
            'r' => 245.0,
            'g' => 240.0,
            'b' => 231.0,
        ),
        'espresso' => array(
            'r' => 45.0,
            'g' => 45.0,
            'b' => 45.0,
        ),
        'eva-dim' => array(
            'r' => 42.0,
            'g' => 59.0,
            'b' => 77.0,
        ),
        'eva' => array(
            'r' => 42.0,
            'g' => 59.0,
            'b' => 77.0,
        ),
        'flat' => array(
            'r' => 44.0,
            'g' => 62.0,
            'b' => 80.0,
        ),
        'framer' => array(
            'r' => 24.0,
            'g' => 24.0,
            'b' => 24.0,
        ),
        'fruit-soda' => array(
            'r' => 241.0,
            'g' => 236.0,
            'b' => 241.0,
        ),
        'gigavolt' => array(
            'r' => 32.0,
            'g' => 33.0,
            'b' => 38.0,
        ),
        'github' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'google-dark' => array(
            'r' => 29.0,
            'g' => 31.0,
            'b' => 33.0,
        ),
        'google-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'grayscale-dark' => array(
            'r' => 16.0,
            'g' => 16.0,
            'b' => 16.0,
        ),
        'grayscale-light' => array(
            'r' => 247.0,
            'g' => 247.0,
            'b' => 247.0,
        ),
        'green-screen' => array(
            'r' => 0.0,
            'g' => 17.0,
            'b' => 0.0,
        ),
        'gruvbox-dark-hard' => array(
            'r' => 29.0,
            'g' => 32.0,
            'b' => 33.0,
        ),
        'gruvbox-dark-medium' => array(
            'r' => 40.0,
            'g' => 40.0,
            'b' => 40.0,
        ),
        'gruvbox-dark-pale' => array(
            'r' => 38.0,
            'g' => 38.0,
            'b' => 38.0,
        ),
        'gruvbox-dark-soft' => array(
            'r' => 50.0,
            'g' => 48.0,
            'b' => 47.0,
        ),
        'gruvbox-light-hard' => array(
            'r' => 249.0,
            'g' => 245.0,
            'b' => 215.0,
        ),
        'gruvbox-light-medium' => array(
            'r' => 251.0,
            'g' => 241.0,
            'b' => 199.0,
        ),
        'gruvbox-light-soft' => array(
            'r' => 242.0,
            'g' => 229.0,
            'b' => 188.0,
        ),
        'hardcore' => array(
            'r' => 33.0,
            'g' => 33.0,
            'b' => 33.0,
        ),
        'harmonic16-dark' => array(
            'r' => 11.0,
            'g' => 28.0,
            'b' => 44.0,
        ),
        'harmonic16-light' => array(
            'r' => 247.0,
            'g' => 249.0,
            'b' => 251.0,
        ),
        'heetch-dark' => array(
            'r' => 25.0,
            'g' => 1.0,
            'b' => 52.0,
        ),
        'heetch-light' => array(
            'r' => 254.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'helios' => array(
            'r' => 29.0,
            'g' => 32.0,
            'b' => 33.0,
        ),
        'hopscotch' => array(
            'r' => 50.0,
            'g' => 41.0,
            'b' => 49.0,
        ),
        'horizon-dark' => array(
            'r' => 28.0,
            'g' => 30.0,
            'b' => 38.0,
        ),
        'horizon-light' => array(
            'r' => 253.0,
            'g' => 240.0,
            'b' => 237.0,
        ),
        'humanoid-dark' => array(
            'r' => 35.0,
            'g' => 38.0,
            'b' => 41.0,
        ),
        'humanoid-light' => array(
            'r' => 248.0,
            'g' => 248.0,
            'b' => 242.0,
        ),
        'ia-dark' => array(
            'r' => 26.0,
            'g' => 26.0,
            'b' => 26.0,
        ),
        'ia-light' => array(
            'r' => 246.0,
            'g' => 246.0,
            'b' => 246.0,
        ),
        'icy-dark' => array(
            'r' => 2.0,
            'g' => 16.0,
            'b' => 18.0,
        ),
        'ir-black' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'isotope' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'kimber' => array(
            'r' => 34.0,
            'g' => 34.0,
            'b' => 34.0,
        ),
        'london-tube' => array(
            'r' => 35.0,
            'g' => 31.0,
            'b' => 32.0,
        ),
        'macintosh' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'marrakesh' => array(
            'r' => 32.0,
            'g' => 22.0,
            'b' => 2.0,
        ),
        'materia' => array(
            'r' => 38.0,
            'g' => 50.0,
            'b' => 56.0,
        ),
        'material-darker' => array(
            'r' => 33.0,
            'g' => 33.0,
            'b' => 33.0,
        ),
        'material-lighter' => array(
            'r' => 250.0,
            'g' => 250.0,
            'b' => 250.0,
        ),
        'material-palenight' => array(
            'r' => 41.0,
            'g' => 45.0,
            'b' => 62.0,
        ),
        'material-vivid' => array(
            'r' => 32.0,
            'g' => 33.0,
            'b' => 36.0,
        ),
        'material' => array(
            'r' => 38.0,
            'g' => 50.0,
            'b' => 56.0,
        ),
        'mellow-purple' => array(
            'r' => 30.0,
            'g' => 5.0,
            'b' => 40.0,
        ),
        'mexico-light' => array(
            'r' => 248.0,
            'g' => 248.0,
            'b' => 248.0,
        ),
        'mocha' => array(
            'r' => 59.0,
            'g' => 50.0,
            'b' => 40.0,
        ),
        'monokai' => array(
            'r' => 39.0,
            'g' => 40.0,
            'b' => 34.0,
        ),
        'nebula' => array(
            'r' => 34.0,
            'g' => 39.0,
            'b' => 59.0,
        ),
        'nord' => array(
            'r' => 46.0,
            'g' => 52.0,
            'b' => 64.0,
        ),
        'nova' => array(
            'r' => 60.0,
            'g' => 76.0,
            'b' => 85.0,
        ),
        'ocean' => array(
            'r' => 43.0,
            'g' => 48.0,
            'b' => 59.0,
        ),
        'oceanicnext' => array(
            'r' => 27.0,
            'g' => 43.0,
            'b' => 52.0,
        ),
        'one-light' => array(
            'r' => 250.0,
            'g' => 250.0,
            'b' => 250.0,
        ),
        'onedark' => array(
            'r' => 40.0,
            'g' => 44.0,
            'b' => 52.0,
        ),
        'outrun-dark' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 42.0,
        ),
        'papercolor-dark' => array(
            'r' => 28.0,
            'g' => 28.0,
            'b' => 28.0,
        ),
        'papercolor-light' => array(
            'r' => 238.0,
            'g' => 238.0,
            'b' => 238.0,
        ),
        'paraiso' => array(
            'r' => 47.0,
            'g' => 30.0,
            'b' => 46.0,
        ),
        'pasque' => array(
            'r' => 39.0,
            'g' => 28.0,
            'b' => 58.0,
        ),
        'phd' => array(
            'r' => 6.0,
            'g' => 18.0,
            'b' => 41.0,
        ),
        'pico' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'pop' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'porple' => array(
            'r' => 41.0,
            'g' => 44.0,
            'b' => 54.0,
        ),
        'qualia' => array(
            'r' => 16.0,
            'g' => 16.0,
            'b' => 16.0,
        ),
        'railscasts' => array(
            'r' => 43.0,
            'g' => 43.0,
            'b' => 43.0,
        ),
        'rebecca' => array(
            'r' => 41.0,
            'g' => 42.0,
            'b' => 68.0,
        ),
        'ros-pine-dawn' => array(
            'r' => 250.0,
            'g' => 244.0,
            'b' => 237.0,
        ),
        'ros-pine-moon' => array(
            'r' => 35.0,
            'g' => 33.0,
            'b' => 54.0,
        ),
        'ros-pine' => array(
            'r' => 25.0,
            'g' => 23.0,
            'b' => 36.0,
        ),
        'sagelight' => array(
            'r' => 248.0,
            'g' => 248.0,
            'b' => 248.0,
        ),
        'sandcastle' => array(
            'r' => 40.0,
            'g' => 44.0,
            'b' => 52.0,
        ),
        'seti-ui' => array(
            'r' => 21.0,
            'g' => 23.0,
            'b' => 24.0,
        ),
        'shapeshifter' => array(
            'r' => 249.0,
            'g' => 249.0,
            'b' => 249.0,
        ),
        'silk-dark' => array(
            'r' => 14.0,
            'g' => 60.0,
            'b' => 70.0,
        ),
        'silk-light' => array(
            'r' => 233.0,
            'g' => 241.0,
            'b' => 239.0,
        ),
        'snazzy' => array(
            'r' => 40.0,
            'g' => 42.0,
            'b' => 54.0,
        ),
        'solar-flare-light' => array(
            'r' => 245.0,
            'g' => 247.0,
            'b' => 250.0,
        ),
        'solar-flare' => array(
            'r' => 24.0,
            'g' => 38.0,
            'b' => 47.0,
        ),
        'solarized-dark' => array(
            'r' => 0.0,
            'g' => 43.0,
            'b' => 54.0,
        ),
        'solarized-light' => array(
            'r' => 253.0,
            'g' => 246.0,
            'b' => 227.0,
        ),
        'spacemacs' => array(
            'r' => 31.0,
            'g' => 32.0,
            'b' => 34.0,
        ),
        'summercamp' => array(
            'r' => 28.0,
            'g' => 24.0,
            'b' => 16.0,
        ),
        'summerfruit-dark' => array(
            'r' => 21.0,
            'g' => 21.0,
            'b' => 21.0,
        ),
        'summerfruit-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'synth-midnight-terminal-dark' => array(
            'r' => 5.0,
            'g' => 6.0,
            'b' => 8.0,
        ),
        'synth-midnight-terminal-light' => array(
            'r' => 221.0,
            'g' => 223.0,
            'b' => 224.0,
        ),
        'tango' => array(
            'r' => 46.0,
            'g' => 52.0,
            'b' => 54.0,
        ),
        'tender' => array(
            'r' => 40.0,
            'g' => 40.0,
            'b' => 40.0,
        ),
        'tomorrow-night' => array(
            'r' => 45.0,
            'g' => 45.0,
            'b' => 45.0,
        ),
        'tomorrow' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'twilight' => array(
            'r' => 30.0,
            'g' => 30.0,
            'b' => 30.0,
        ),
        'unikitty-dark' => array(
            'r' => 46.0,
            'g' => 42.0,
            'b' => 49.0,
        ),
        'unikitty-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'vulcan' => array(
            'r' => 4.0,
            'g' => 21.0,
            'b' => 35.0,
        ),
        'windows-10-light' => array(
            'r' => 242.0,
            'g' => 242.0,
            'b' => 242.0,
        ),
        'windows-10' => array(
            'r' => 12.0,
            'g' => 12.0,
            'b' => 12.0,
        ),
        'windows-95-light' => array(
            'r' => 252.0,
            'g' => 252.0,
            'b' => 252.0,
        ),
        'windows-95' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'windows-high-contrast-light' => array(
            'r' => 252.0,
            'g' => 252.0,
            'b' => 252.0,
        ),
        'windows-high-contrast' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'windows-nt-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'windows-nt' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'woodland' => array(
            'r' => 35.0,
            'g' => 30.0,
            'b' => 24.0,
        ),
        'xcode-dusk' => array(
            'r' => 40.0,
            'g' => 43.0,
            'b' => 53.0,
        ),
        'zenburn' => array(
            'r' => 56.0,
            'g' => 56.0,
            'b' => 56.0,
        ),
        'brown-paper' => array(
            'r' => 183.0,
            'g' => 166.0,
            'b' => 142.0,
        ),
        'codepen-embed' => array(
            'r' => 34.0,
            'g' => 34.0,
            'b' => 34.0,
        ),
        'color-brewer' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'dark' => array(
            'r' => 48.0,
            'g' => 48.0,
            'b' => 48.0,
        ),
        'default' => array(
            'r' => 243.0,
            'g' => 243.0,
            'b' => 243.0,
        ),
        'devibeans' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'docco' => array(
            'r' => 248.0,
            'g' => 248.0,
            'b' => 255.0,
        ),
        'far' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 128.0,
        ),
        'felipec' => array(
            'r' => 30.0,
            'g' => 30.0,
            'b' => 34.0,
        ),
        'foundation' => array(
            'r' => 238.0,
            'g' => 238.0,
            'b' => 238.0,
        ),
        'github-dark-dimmed' => array(
            'r' => 34.0,
            'g' => 39.0,
            'b' => 46.0,
        ),
        'github-dark' => array(
            'r' => 13.0,
            'g' => 17.0,
            'b' => 23.0,
        ),
        'gml' => array(
            'r' => 34.0,
            'g' => 34.0,
            'b' => 34.0,
        ),
        'googlecode' => array(
            'r' => 255,
            'g' => 255,
            'b' => 255,
        ),
        'gradient-dark' => array(
            'r' => 101.0,
            'g' => 36.0,
            'b' => 135.0,
        ),
        'gradient-light' => array(
            'r' => 249.0,
            'g' => 204.0,
            'b' => 255.0,
        ),
        'grayscale' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'hybrid' => array(
            'r' => 29.0,
            'g' => 31.0,
            'b' => 33.0,
        ),
        'idea' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'intellij-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'isbl-editor-dark' => array(
            'r' => 64.0,
            'g' => 64.0,
            'b' => 64.0,
        ),
        'isbl-editor-light' => array(
            'r' => 255,
            'g' => 255,
            'b' => 255,
        ),
        'kimbie-dark' => array(
            'r' => 34.0,
            'g' => 26.0,
            'b' => 15.0,
        ),
        'kimbie-light' => array(
            'r' => 251.0,
            'g' => 235.0,
            'b' => 212.0,
        ),
        'lightfair' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'lioshi' => array(
            'r' => 48.0,
            'g' => 48.0,
            'b' => 48.0,
        ),
        'magula' => array(
            'r' => 244.0,
            'g' => 244.0,
            'b' => 244.0,
        ),
        'mono-blue' => array(
            'r' => 234.0,
            'g' => 238.0,
            'b' => 243.0,
        ),
        'monokai-sublime' => array(
            'r' => 35.0,
            'g' => 36.0,
            'b' => 31.0,
        ),
        'night-owl' => array(
            'r' => 1.0,
            'g' => 22.0,
            'b' => 39.0,
        ),
        'nnfx-dark' => array(
            'r' => 51.0,
            'g' => 51.0,
            'b' => 51.0,
        ),
        'nnfx-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'obsidian' => array(
            'r' => 40.0,
            'g' => 43.0,
            'b' => 46.0,
        ),
        'panda-syntax-dark' => array(
            'r' => 42.0,
            'g' => 44.0,
            'b' => 45.0,
        ),
        'panda-syntax-light' => array(
            'r' => 230.0,
            'g' => 230.0,
            'b' => 230.0,
        ),
        'paraiso-dark' => array(
            'r' => 47.0,
            'g' => 30.0,
            'b' => 46.0,
        ),
        'paraiso-light' => array(
            'r' => 231.0,
            'g' => 233.0,
            'b' => 219.0,
        ),
        'pojoaque' => array(
            'r' => 24.0,
            'g' => 25.0,
            'b' => 20.0,
        ),
        'purebasic' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 223.0,
        ),
        'qtcreator-dark' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'qtcreator-light' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'rainbow' => array(
            'r' => 71.0,
            'g' => 73.0,
            'b' => 73.0,
        ),
        'routeros' => array(
            'r' => 240.0,
            'g' => 240.0,
            'b' => 240.0,
        ),
        'school-book' => array(
            'r' => 246.0,
            'g' => 245.0,
            'b' => 178.0,
        ),
        'shades-of-purple' => array(
            'r' => 45.0,
            'g' => 43.0,
            'b' => 87.0,
        ),
        'srcery' => array(
            'r' => 28.0,
            'g' => 27.0,
            'b' => 25.0,
        ),
        'stackoverflow-dark' => array(
            'r' => 28.0,
            'g' => 27.0,
            'b' => 27.0,
        ),
        'stackoverflow-light' => array(
            'r' => 246.0,
            'g' => 246.0,
            'b' => 246.0,
        ),
        'sunburst' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
        'tokyo-night-dark' => array(
            'r' => 26.0,
            'g' => 27.0,
            'b' => 38.0,
        ),
        'tokyo-night-light' => array(
            'r' => 213.0,
            'g' => 214.0,
            'b' => 219.0,
        ),
        'tomorrow-night-blue' => array(
            'r' => 0.0,
            'g' => 36.0,
            'b' => 81.0,
        ),
        'tomorrow-night-bright' => array(
            'r' => 255,
            'g' => 255,
            'b' => 255,
        ),
        'vs' => array(
            'r' => 255,
            'g' => 255,
            'b' => 255,
        ),
        'vs2015' => array(
            'r' => 30.0,
            'g' => 30.0,
            'b' => 30.0,
        ),
        'xcode' => array(
            'r' => 255.0,
            'g' => 255.0,
            'b' => 255.0,
        ),
        'xt256' => array(
            'r' => 0.0,
            'g' => 0.0,
            'b' => 0.0,
        ),
    );

    if (!isset($colors[$theme])) {
        throw new DomainException("There is no stylesheet by the name of '$theme'");
    }

    return $colors[$theme];
}
